# ref: https://docs.github.com/ja/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository
name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
  - LeoAndo
body:
  - type: markdown
    attributes:
      value: |
        このバグレポートにご記入いただきありがとうございます。
  - type: textarea
    id: what-happened
    attributes:
      label: 問題内容
      description: できるだけ詳しく問題内容の記載をお願いします🙏
      placeholder: 必須の入力項目になります。
      value: "バグが発生しました！"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: アプリバージョン
      description: 問題が発生したアプリのバージョンを教えてください
      options:
        - 1.0.0
        - 1.1.0
        - 1.1.1
        - 1.2.1
        - 1.3.0
        - 1.4.0
        - 1.5.0
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Android OSバージョン
      description: どのOSバージョンで問題が発生していますか?
      multiple: true
      options:
        - 10
        - 11
        - 12
        - 13
        - 14
        - 15
        - 16
        - 17
  - type: textarea
    id: logs
    attributes:
      label: エラーログ
      description: 関連するログ出力をコピーして貼り付けてください。自動的にコードフォーマットされるため、バッククォートは必要ありません。
      render: shell
