name: Android Release

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    
    steps:
    - uses: actions/checkout@v3
    
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
        
    - name: Create release.keystore
      run: echo "${{ secrets.ANDROID_STORE_BASE64 }}" | base64 -d > release.keystore

    - name: Create local.properties
      env:
        ANDROID_STORE_PASSWORD: ${{ secrets.ANDROID_STORE_PASSWORD }}
        ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
        ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}
      run: |
        echo "ANDROID_STORE_PASSWORD=$ANDROID_STORE_PASSWORD" >> local.properties
        echo "ANDROID_KEY_ALIAS=$ANDROID_KEY_ALIAS" >> local.properties
        echo "ANDROID_KEY_PASSWORD=$ANDROID_KEY_PASSWORD" >> local.properties
        echo "MAPS_API_KEY=$MAPS_API_KEY" >> local.properties

    - name: Release Build tasks (apk and aab)
      run: |
        ./gradlew assembleRelease
        ./gradlew bundleRelease
    
    # https://github.com/softprops/action-gh-release#%EF%B8%8F-uploading-release-assets
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          app/build/outputs/apk/simple/release/app-simple-release.apk
          app/build/outputs/bundle/simpleRelease/app-simple-release.aab
          app/build/outputs/apk/bottombar/release/app-bottombar-release.apk
          app/build/outputs/bundle/bottombarRelease/app-bottombar-release.aab
          app/build/outputs/apk/drawer/release/app-drawer-release.apk
          app/build/outputs/bundle/drawerRelease/app-drawer-release.aab